spring:
  profiles:
    include: jpa, redis


# SampleController - thread pool test 의존
# 시나리오 1 ) 10, 10, 10   모든 설정이 충분할 때
# 시나리오 2 ) 1, 10, 10    acceptCount만 부족할 때
# 시나리오 3 ) 1, 5, 10     acceptCount와 maxConnections가 부족할 때
# 시나리오 4 ) 3, 5, 10    maxThreads만 부족한 경우
server:
  tomcat:
    accept-count: 3
    max-connections: 5
    threads:
      max: 10