###
GET http://localhost:8080/session
Content-Type: application/json

###
GET http://localhost:8080/attribute/a/value/aBalue
Content-Type: application/json

###
GET http://localhost:8080/attribute/b/value/bBalue
Content-Type: application/json

### basic
GET http://localhost:8080/session-key/yul?type=default
Content-Type: application/json

### dto
GET http://localhost:8080/session-key/yeon?type=dto
Content-Type: application/json


### custom
GET http://localhost:8080/user/my-page?zuid=minyul
Content-Type: application/json